const ACTION_TYPES = {
  UPDATE_FILTER_SETTING: 'UPDATE_FILTER_SETTING',
  FETCH_IMAGES: 'FETCH_IMAGES',
  TOGGLE_PRIMARY_SPINNER: 'TOGGLE_PRIMARY_SPINNER',
  RECEIVE_ERROR: 'RECEIVE_ERROR',
  CLEAR_ERROR: 'CLEAR_ERROR',
}

export default ACTION_TYPES
